// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/category/category.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/category/category.go -destination=mocks/domain/category/mock_category.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	category "github.com/qkitzero/combination-service/internal/domain/category"
	language "github.com/qkitzero/combination-service/internal/domain/language"
	gomock "go.uber.org/mock/gomock"
)

// MockCategory is a mock of Category interface.
type MockCategory struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryMockRecorder
	isgomock struct{}
}

// MockCategoryMockRecorder is the mock recorder for MockCategory.
type MockCategoryMockRecorder struct {
	mock *MockCategory
}

// NewMockCategory creates a new mock instance.
func NewMockCategory(ctrl *gomock.Controller) *MockCategory {
	mock := &MockCategory{ctrl: ctrl}
	mock.recorder = &MockCategoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategory) EXPECT() *MockCategoryMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockCategory) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockCategoryMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockCategory)(nil).CreatedAt))
}

// ID mocks base method.
func (m *MockCategory) ID() category.CategoryID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(category.CategoryID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockCategoryMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockCategory)(nil).ID))
}

// Language mocks base method.
func (m *MockCategory) Language() language.Language {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Language")
	ret0, _ := ret[0].(language.Language)
	return ret0
}

// Language indicates an expected call of Language.
func (mr *MockCategoryMockRecorder) Language() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Language", reflect.TypeOf((*MockCategory)(nil).Language))
}

// Name mocks base method.
func (m *MockCategory) Name() category.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(category.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCategoryMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCategory)(nil).Name))
}
