// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/rule/rule.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/rule/rule.go -destination=mocks/domain/rule/mock_rule.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	element "github.com/qkitzero/combination-service/internal/domain/element"
	gomock "go.uber.org/mock/gomock"
)

// MockRule is a mock of Rule interface.
type MockRule struct {
	ctrl     *gomock.Controller
	recorder *MockRuleMockRecorder
	isgomock struct{}
}

// MockRuleMockRecorder is the mock recorder for MockRule.
type MockRuleMockRecorder struct {
	mock *MockRule
}

// NewMockRule creates a new mock instance.
func NewMockRule(ctrl *gomock.Controller) *MockRule {
	mock := &MockRule{ctrl: ctrl}
	mock.recorder = &MockRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRule) EXPECT() *MockRuleMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockRule) Apply(elements []element.Element) ([]element.Element, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", elements)
	ret0, _ := ret[0].([]element.Element)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockRuleMockRecorder) Apply(elements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockRule)(nil).Apply), elements)
}
