// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/rule/strategy.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/rule/strategy.go -destination=mocks/domain/rule/mock_strategy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	element "github.com/qkitzero/combination-service/internal/domain/element"
	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
	isgomock struct{}
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// Select mocks base method.
func (m *MockStrategy) Select(count int, elements []element.Element) ([]element.Element, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", count, elements)
	ret0, _ := ret[0].([]element.Element)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockStrategyMockRecorder) Select(count, elements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockStrategy)(nil).Select), count, elements)
}
