// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/combination/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/combination/usecase.go -destination=mocks/application/combination/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	category "github.com/qkitzero/combination-service/internal/domain/category"
	element "github.com/qkitzero/combination-service/internal/domain/element"
	gomock "go.uber.org/mock/gomock"
)

// MockCombinationUsecase is a mock of CombinationUsecase interface.
type MockCombinationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCombinationUsecaseMockRecorder
	isgomock struct{}
}

// MockCombinationUsecaseMockRecorder is the mock recorder for MockCombinationUsecase.
type MockCombinationUsecaseMockRecorder struct {
	mock *MockCombinationUsecase
}

// NewMockCombinationUsecase creates a new mock instance.
func NewMockCombinationUsecase(ctrl *gomock.Controller) *MockCombinationUsecase {
	mock := &MockCombinationUsecase{ctrl: ctrl}
	mock.recorder = &MockCombinationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCombinationUsecase) EXPECT() *MockCombinationUsecaseMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCombinationUsecase) CreateCategory(name string) (category.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", name)
	ret0, _ := ret[0].(category.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCombinationUsecaseMockRecorder) CreateCategory(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCombinationUsecase)(nil).CreateCategory), name)
}

// CreateElement mocks base method.
func (m *MockCombinationUsecase) CreateElement(name string) (element.Element, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateElement", name)
	ret0, _ := ret[0].(element.Element)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateElement indicates an expected call of CreateElement.
func (mr *MockCombinationUsecaseMockRecorder) CreateElement(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateElement", reflect.TypeOf((*MockCombinationUsecase)(nil).CreateElement), name)
}
