// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/combination/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/combination/usecase.go -destination=mocks/application/combination/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	category "github.com/qkitzero/combination-service/internal/domain/category"
	element "github.com/qkitzero/combination-service/internal/domain/element"
	gomock "go.uber.org/mock/gomock"
)

// MockCombinationUsecase is a mock of CombinationUsecase interface.
type MockCombinationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCombinationUsecaseMockRecorder
	isgomock struct{}
}

// MockCombinationUsecaseMockRecorder is the mock recorder for MockCombinationUsecase.
type MockCombinationUsecaseMockRecorder struct {
	mock *MockCombinationUsecase
}

// NewMockCombinationUsecase creates a new mock instance.
func NewMockCombinationUsecase(ctrl *gomock.Controller) *MockCombinationUsecase {
	mock := &MockCombinationUsecase{ctrl: ctrl}
	mock.recorder = &MockCombinationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCombinationUsecase) EXPECT() *MockCombinationUsecaseMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCombinationUsecase) CreateCategory(name, languageCode string) (category.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", name, languageCode)
	ret0, _ := ret[0].(category.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCombinationUsecaseMockRecorder) CreateCategory(name, languageCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCombinationUsecase)(nil).CreateCategory), name, languageCode)
}

// CreateElement mocks base method.
func (m *MockCombinationUsecase) CreateElement(name, languageCode string, categoryIDs []string) (element.Element, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateElement", name, languageCode, categoryIDs)
	ret0, _ := ret[0].(element.Element)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateElement indicates an expected call of CreateElement.
func (mr *MockCombinationUsecaseMockRecorder) CreateElement(name, languageCode, categoryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateElement", reflect.TypeOf((*MockCombinationUsecase)(nil).CreateElement), name, languageCode, categoryIDs)
}

// GetCombination mocks base method.
func (m *MockCombinationUsecase) GetCombination(count int) ([]element.Element, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCombination", count)
	ret0, _ := ret[0].([]element.Element)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCombination indicates an expected call of GetCombination.
func (mr *MockCombinationUsecaseMockRecorder) GetCombination(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCombination", reflect.TypeOf((*MockCombinationUsecase)(nil).GetCombination), count)
}

// ListCategories mocks base method.
func (m *MockCombinationUsecase) ListCategories() ([]category.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories")
	ret0, _ := ret[0].([]category.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockCombinationUsecaseMockRecorder) ListCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCombinationUsecase)(nil).ListCategories))
}

// ListElements mocks base method.
func (m *MockCombinationUsecase) ListElements() ([]element.Element, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListElements")
	ret0, _ := ret[0].([]element.Element)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListElements indicates an expected call of ListElements.
func (mr *MockCombinationUsecaseMockRecorder) ListElements() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListElements", reflect.TypeOf((*MockCombinationUsecase)(nil).ListElements))
}
