// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/language/language.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/language/language.go -destination=mocks/domain/language/mock_language.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
