// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/element/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/element/repository.go -destination=mocks/domain/element/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	element "github.com/qkitzero/combination-service/internal/domain/element"
	gomock "go.uber.org/mock/gomock"
)

// MockElementRepository is a mock of ElementRepository interface.
type MockElementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockElementRepositoryMockRecorder
	isgomock struct{}
}

// MockElementRepositoryMockRecorder is the mock recorder for MockElementRepository.
type MockElementRepositoryMockRecorder struct {
	mock *MockElementRepository
}

// NewMockElementRepository creates a new mock instance.
func NewMockElementRepository(ctrl *gomock.Controller) *MockElementRepository {
	mock := &MockElementRepository{ctrl: ctrl}
	mock.recorder = &MockElementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElementRepository) EXPECT() *MockElementRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockElementRepository) Create(arg0 element.Element) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockElementRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockElementRepository)(nil).Create), arg0)
}

// FindAll mocks base method.
func (m *MockElementRepository) FindAll() ([]element.Element, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]element.Element)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockElementRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockElementRepository)(nil).FindAll))
}
