// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/element/element.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/element/element.go -destination=mocks/domain/element/mock_element.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	element "github.com/qkitzero/combination-service/internal/domain/element"
	gomock "go.uber.org/mock/gomock"
)

// MockElement is a mock of Element interface.
type MockElement struct {
	ctrl     *gomock.Controller
	recorder *MockElementMockRecorder
	isgomock struct{}
}

// MockElementMockRecorder is the mock recorder for MockElement.
type MockElementMockRecorder struct {
	mock *MockElement
}

// NewMockElement creates a new mock instance.
func NewMockElement(ctrl *gomock.Controller) *MockElement {
	mock := &MockElement{ctrl: ctrl}
	mock.recorder = &MockElementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElement) EXPECT() *MockElementMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockElement) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockElementMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockElement)(nil).CreatedAt))
}

// ID mocks base method.
func (m *MockElement) ID() element.ElementID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(element.ElementID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockElementMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockElement)(nil).ID))
}

// Name mocks base method.
func (m *MockElement) Name() element.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(element.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockElementMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockElement)(nil).Name))
}
